version: "3.8"

services:
  portal:
    build: ./portal
    ports:
      - "3000:3000"
    depends_on:
      - amazon-clone

  amazon-clone:
    build: ./websites/amazon-clone
    ports:
      - "3001:3000"  # Container port 3000 mapped to host 3001